### PR TITLE
Bunch of tentative changes required to upgrade GridapPardiso to Gridap 0.16

### PR DESCRIPTION
**Pull request by amartinhuertas**
Hi @fverdugo, 

find a tentative set of changes required to upgrade GridapPardiso to Gridap 0.16. Some comments:

* I have upgraded the version of GridapPardiso to `0.5.0`. Is this actually needed?
* I have changed the compat version of Gridap to 0.15, 0.16, although I only tried with 0.16. 
* I explicitly added some function definition stataments [here](https://github.com/gridap/GridapPardiso.jl/commit/48e5fd1a03cac7c9018828eaa388ad4141a4dabe#diff-c82de737873a33cff8dc807e2dc361849aad3d7c2365dfb4ae6fee732fbb5517R76). I think these are no longer available in `SparseMatricesCSR` (perhaps with another name?)  but required by `GridapPardiso`. 

Thanks!
@amartinhuertas

### CODE REVIEW

**Review by fverdugo — APPROVED** [review]

**Comment by fverdugo** [comment]
CI is not running since it is still Travis-based...

**Comment by amartinhuertas** [comment]
>CI is not running since it is still Travis-based...

Ok, I will do it.

**Comment by amartinhuertas** [comment]
> CI is not running since it is still Travis-based...

Ok, done. It took me more time than expected ... not easy to set up + Pardiso MKL in Github actions. 

You can proceed with your code review.

Thanks!

**Comment by amartinhuertas** [comment]
Can we release the new version of `GridapPardiso` ?

**Comment by fverdugo** [comment]
Yes sure!

**Pull request merged**
